"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 13:33:48.574743
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_grade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_grade_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('dataset_settings',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('use_nominal_diameter', sa.Boolean(), nullable=False),
    sa.Column('nominal_diameter', sa.Integer(), nullable=False),
    sa.Column('use_nominal_length', sa.Boolean(), nullable=False),
    sa.Column('nominal_length_incr_m', sa.Float(), nullable=False),
    sa.Column('use_nominal_taper', sa.Boolean(), nullable=False),
    sa.Column('nominal_taper_mm_per_m', sa.Float(), nullable=False),
    sa.Column('disc_separation_cm', sa.Float(), nullable=False),
    sa.Column('points_per_disc', sa.Integer(), nullable=False),
    sa.Column('discretised', sa.Boolean(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('chip_price', sa.Float(), nullable=False),
    sa.Column('sawdust_price', sa.Float(), nullable=False),
    sa.Column('pct_fines', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('length_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_m', sa.Float(), nullable=False),
    sa.Column('max_m', sa.Float(), nullable=False),
    sa.Column('incr_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name')
    )
    with op.batch_alter_table('length_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_length_class_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('log_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('min_diameter_cm', sa.Float(), nullable=False),
    sa.Column('max_diameter_cm', sa.Float(), nullable=False),
    sa.Column('min_length_m', sa.Float(), nullable=False),
    sa.Column('max_length_m', sa.Float(), nullable=False),
    sa.Column('length_incr_m', sa.Float(), nullable=False),
    sa.Column('min_taper', sa.Float(), nullable=False),
    sa.Column('max_taper', sa.Float(), nullable=False),
    sa.Column('min_sweep', sa.Float(), nullable=False),
    sa.Column('max_sweep', sa.Float(), nullable=False),
    sa.Column('min_ovality', sa.Float(), nullable=False),
    sa.Column('max_ovality', sa.Float(), nullable=False),
    sa.Column('min_defect_core', sa.Float(), nullable=False),
    sa.Column('max_defect_core', sa.Float(), nullable=False),
    sa.Column('log_price', sa.Float(), nullable=False),
    sa.Column('log_price_placeholder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_class_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('log_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_grade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_grade_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('production_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('saw_type', sa.Integer(), nullable=False),
    sa.Column('primary_machine', sa.String(length=50), nullable=False),
    sa.Column('secondary_machine', sa.String(length=50), nullable=False),
    sa.Column('primary_kerf', sa.Float(), nullable=False),
    sa.Column('primary_outside_kerf', sa.Float(), nullable=True),
    sa.Column('primary_outside_blades', sa.Integer(), nullable=False),
    sa.Column('secondary_kerf', sa.Float(), nullable=False),
    sa.Column('secondary_outside_kerf', sa.Float(), nullable=True),
    sa.Column('secondary_outside_blades', sa.Integer(), nullable=False),
    sa.Column('primary_resaw', sa.Boolean(), nullable=False),
    sa.Column('primary_resaw_kerf', sa.Float(), nullable=False),
    sa.Column('secondary_resaw', sa.Boolean(), nullable=False),
    sa.Column('secondary_resaw_kerf', sa.Float(), nullable=False),
    sa.Column('cant_guiding', sa.Integer(), nullable=False),
    sa.Column('max_sweep', sa.Float(), nullable=False),
    sa.Column('log_rotation_deg', sa.Float(), nullable=False),
    sa.Column('log_misalignment_mm', sa.Float(), nullable=False),
    sa.Column('primary_offset_mm', sa.Float(), nullable=False),
    sa.Column('cant_misalignment_mm', sa.Float(), nullable=False),
    sa.Column('secondary_offset_mm', sa.Float(), nullable=False),
    sa.Column('edging_objective', sa.Integer(), nullable=False),
    sa.Column('edger_blades', sa.Integer(), nullable=False),
    sa.Column('edger_kerf', sa.Float(), nullable=False),
    sa.Column('second_board_width', sa.String(length=20), nullable=False),
    sa.Column('max_boards_per_flitch', sa.Integer(), nullable=False),
    sa.Column('kerfs_placeholder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_line_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('thickness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dry', sa.Float(), nullable=False),
    sa.Column('wet', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'dry')
    )
    with op.batch_alter_table('thickness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thickness_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('width',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dry', sa.Float(), nullable=False),
    sa.Column('wet', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'dry')
    )
    with op.batch_alter_table('width', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_width_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('centre_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('width_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thickness_id'], ['thickness.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['width_id'], ['width.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thickness_id', 'width_id')
    )
    with op.batch_alter_table('centre_board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_centre_board_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('combination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('width_id', sa.Integer(), nullable=False),
    sa.Column('length_class_id', sa.Integer(), nullable=False),
    sa.Column('board_grade_id', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_placeholder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_grade_id'], ['board_grade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['length_class_id'], ['length_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thickness_id'], ['thickness.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['width_id'], ['width.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thickness_id', 'width_id', 'length_class_id', 'board_grade_id')
    )
    with op.batch_alter_table('combination', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combination_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('grade_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('width_id', sa.Integer(), nullable=False),
    sa.Column('log_grade_id', sa.Integer(), nullable=False),
    sa.Column('board_grade_id', sa.Integer(), nullable=False),
    sa.Column('p_zero', sa.Float(), nullable=False),
    sa.Column('p_fifty', sa.Float(), nullable=False),
    sa.Column('p_ninety_nine', sa.Float(), nullable=False),
    sa.Column('p_hundred', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['board_grade_id'], ['board_grade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_grade_id'], ['log_grade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thickness_id'], ['thickness.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['width_id'], ['width.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_output_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('log_no', sa.Integer(), nullable=False),
    sa.Column('sed_cm', sa.Float(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('taper', sa.Float(), nullable=False),
    sa.Column('sweep_mm', sa.Float(), nullable=False),
    sa.Column('ovality', sa.Float(), nullable=False),
    sa.Column('defect_core_cm', sa.Float(), nullable=False),
    sa.Column('log_grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_grade_id'], ['log_grade.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('log_class_grade',
    sa.Column('log_class_id', sa.Integer(), nullable=False),
    sa.Column('log_grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_class_id'], ['log_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_grade_id'], ['log_grade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_class_id', 'log_grade_id')
    )
    op.create_table('log_generator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('no_of_logs', sa.Integer(), nullable=False),
    sa.Column('fixed_seed', sa.Boolean(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('min_diameter', sa.Float(), nullable=False),
    sa.Column('max_diameter', sa.Float(), nullable=False),
    sa.Column('diameter_distr', sa.Integer(), nullable=False),
    sa.Column('min_length', sa.Float(), nullable=False),
    sa.Column('max_length', sa.Float(), nullable=False),
    sa.Column('length_incr', sa.Float(), nullable=False),
    sa.Column('length_distr', sa.Integer(), nullable=False),
    sa.Column('min_taper', sa.Float(), nullable=False),
    sa.Column('max_taper', sa.Float(), nullable=False),
    sa.Column('taper_distr', sa.Integer(), nullable=False),
    sa.Column('min_sweep', sa.Float(), nullable=False),
    sa.Column('max_sweep', sa.Float(), nullable=False),
    sa.Column('sweep_distr', sa.Integer(), nullable=False),
    sa.Column('min_ovality', sa.Float(), nullable=False),
    sa.Column('max_ovality', sa.Float(), nullable=False),
    sa.Column('ovality_distr', sa.Integer(), nullable=False),
    sa.Column('min_defect_core', sa.Float(), nullable=False),
    sa.Column('max_defect_core', sa.Float(), nullable=False),
    sa.Column('defect_core_distr', sa.Integer(), nullable=False),
    sa.Column('log_grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_grade_id'], ['log_grade.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_generator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_generator_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('run_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('line_name', sa.String(length=100), nullable=False),
    sa.Column('class_no', sa.Integer(), nullable=False),
    sa.Column('pattern_no', sa.Integer(), nullable=False),
    sa.Column('primary', sa.String(length=200), nullable=False),
    sa.Column('secondary', sa.String(length=200), nullable=False),
    sa.Column('diameter_range', sa.String(length=50), nullable=False),
    sa.Column('log_price', sa.Float(), nullable=False),
    sa.Column('chip_price', sa.Float(), nullable=False),
    sa.Column('sawdust_price', sa.Float(), nullable=False),
    sa.Column('pct_fines', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_pattern', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_pattern_run_id'), ['run_id'], unique=False)

    op.create_table('saw_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('log_class_id', sa.Integer(), nullable=False),
    sa.Column('pattern_no', sa.Integer(), nullable=False),
    sa.Column('primary', sa.String(length=200), nullable=False),
    sa.Column('secondary', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_id'], ['production_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_class_id'], ['log_class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saw_pattern', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saw_pattern_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('wane_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('width_id', sa.Integer(), nullable=False),
    sa.Column('thickness_pct', sa.Float(), nullable=False),
    sa.Column('width_pct', sa.Float(), nullable=False),
    sa.Column('length_wane', sa.Float(), nullable=False),
    sa.Column('length_wane_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thickness_id'], ['thickness.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['width_id'], ['width.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thickness_id', 'width_id')
    )
    with op.batch_alter_table('wane_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wane_rule_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('run_board_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_pattern_id', sa.Integer(), nullable=False),
    sa.Column('log_no', sa.Integer(), nullable=False),
    sa.Column('board_type', sa.Integer(), nullable=False),
    sa.Column('board_no', sa.Integer(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('left', sa.Float(), nullable=False),
    sa.Column('right', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('front_m', sa.Float(), nullable=False),
    sa.Column('back_m', sa.Float(), nullable=False),
    sa.Column('resawn', sa.Boolean(), nullable=False),
    sa.Column('resaw_position', sa.Float(), nullable=False),
    sa.Column('edged', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.String(length=100), nullable=False),
    sa.Column('dry_volume', sa.Float(), nullable=False),
    sa.Column('wet_volume', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_pattern_id'], ['run_pattern.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_board_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_board_result_run_pattern_id'), ['run_pattern_id'], unique=False)

    op.create_table('run_log_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_pattern_id', sa.Integer(), nullable=False),
    sa.Column('log_no', sa.Integer(), nullable=False),
    sa.Column('sed_cm', sa.Float(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('log_volume', sa.Float(), nullable=False),
    sa.Column('dry_volume', sa.Float(), nullable=False),
    sa.Column('wet_volume', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sawdust_volume', sa.Float(), nullable=False),
    sa.Column('chip_volume', sa.Float(), nullable=False),
    sa.Column('boards', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_pattern_id'], ['run_pattern.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_log_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_log_result_run_pattern_id'), ['run_pattern_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_log_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_log_result_run_pattern_id'))

    op.drop_table('run_log_result')
    with op.batch_alter_table('run_board_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_board_result_run_pattern_id'))

    op.drop_table('run_board_result')
    with op.batch_alter_table('wane_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wane_rule_dataset_id'))

    op.drop_table('wane_rule')
    with op.batch_alter_table('saw_pattern', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saw_pattern_dataset_id'))

    op.drop_table('saw_pattern')
    with op.batch_alter_table('run_pattern', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_pattern_run_id'))

    op.drop_table('run_pattern')
    with op.batch_alter_table('log_generator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_generator_dataset_id'))

    op.drop_table('log_generator')
    op.drop_table('log_class_grade')
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_dataset_id'))

    op.drop_table('log')
    with op.batch_alter_table('grade_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_output_dataset_id'))

    op.drop_table('grade_output')
    with op.batch_alter_table('combination', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combination_dataset_id'))

    op.drop_table('combination')
    with op.batch_alter_table('centre_board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_centre_board_dataset_id'))

    op.drop_table('centre_board')
    with op.batch_alter_table('width', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_width_dataset_id'))

    op.drop_table('width')
    with op.batch_alter_table('thickness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thickness_dataset_id'))

    op.drop_table('thickness')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_dataset_id'))

    op.drop_table('run')
    with op.batch_alter_table('production_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_line_dataset_id'))

    op.drop_table('production_line')
    with op.batch_alter_table('log_grade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_grade_dataset_id'))

    op.drop_table('log_grade')
    with op.batch_alter_table('log_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_class_dataset_id'))

    op.drop_table('log_class')
    with op.batch_alter_table('length_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_length_class_dataset_id'))

    op.drop_table('length_class')
    op.drop_table('dataset_settings')
    with op.batch_alter_table('board_grade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_grade_dataset_id'))

    op.drop_table('board_grade')
    op.drop_table('dataset')
    # ### end Alembic commands ###
