"""phase 4 settings and board pieces

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 05:44:04.633728
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arris_small_end', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('real_logs', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('diameter_variation', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('taper_variation', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('sweep_variation', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ovality_variation', sa.Float(), server_default='0', nullable=False))

    with op.batch_alter_table('run_board_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piece', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('core_share', sa.Float(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_board_result', schema=None) as batch_op:
        batch_op.drop_column('core_share')
        batch_op.drop_column('piece')

    with op.batch_alter_table('dataset_settings', schema=None) as batch_op:
        batch_op.drop_column('ovality_variation')
        batch_op.drop_column('sweep_variation')
        batch_op.drop_column('taper_variation')
        batch_op.drop_column('diameter_variation')
        batch_op.drop_column('real_logs')
        batch_op.drop_column('arris_small_end')

    # ### end Alembic commands ###
