"""fixed edger spacing

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-09 07:10:47.677964
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edger_spacing', sa.String(length=200), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_line', schema=None) as batch_op:
        batch_op.drop_column('edger_spacing')

    # ### end Alembic commands ###
